### ISSUE TITLE
Feature Request: Pause/Play

### ISSUE THREAD

**Issue by leavittx** [web-crafters-lab/auto-type-issues#1]
What if we could have a pause/play hotkey while typing the code?
Actually it might be essential for tutorials recording, when sometimes you need more time to explain typed code block

**Comment by mohametalmeari** [comment]
Hi @leavittx, thank you for the suggestion, you're right, a pause/play hotkey would be very helpful, especially for recording tutorials. There's currently a hotkey for controlling speed, and I'm considering either upgrading that function or creating a similar one for pause/play functionality.
