### ISSUE TITLE
Pressing Alt-T while still typing the current file should not start typing next one in parallel

### ISSUE THREAD

**Issue by leavittx** [web-crafters-lab/auto-type-issues#4]
When the current code is being typed, and I press Alt-T, it starts to type next one in parallel.
I suspect there are two possible fixes:
1. Force type the rest of the current file and stop
2. Force type the rest of the current file and start typing next one

I personally prefer the first option :)

**Comment by mohametalmeari** [comment]
Yes, I noticed a bug where two code snippets could be typed simultaneously. I resolved this issue by stopping the current snippet and then allowing a new one to start.
