### ISSUE TITLE
Feature Request: change typing speed using a new action

### ISSUE THREAD

**Issue by leavittx** [web-crafters-lab/auto-type-issues#5]
I think it would be neat to be able to change the typing speed during the typing process.
Something like
🐌 - switch to Slower speed
🚶 - switch to Normal speed
🚗 - switch to Fast speed
🚀 - switch to Faster speed

**Comment by mohametalmeari** [comment]
Actually, it’s possible to change the typing speed during typing in the current version of the extension, but you need to open the speed menu, which I understand is not convenient for recording a tutorial. For this reason, I’m working on adding hotkeys for changing speed. I like the emojis though 😊, and I might consider adding them to the speed menu.
